content/urls.py
from django.conf.urls import url
from . import views

app_name = 'content'

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^home$', views.HomeView.as_view(), name='home'),
	url(r'^post/$', views.PostListView.as_view(), name='post-list'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.PostView.as_view(), name='post'),
	url(r'^questions$', views.QuestionsView.as_view(), name='questions'),
	url(r'^question/(?P<pk>[0-9]+)/$', views.QuestionDetailView.as_view(), name='question-detail'),
	url(r'^solar-system/$', views.SolarView.as_view(), name='solar'),
]

spaceinschool/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('content.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

content/models.py
from django.db import models
from django.utils import timezone

class Posts(models.Model):
	class Meta:
		verbose_name = 'Статья'
		verbose_name_plural = 'Статьи'

	title = models.CharField(max_length=500, verbose_name='Заголовок')
	post_short = models.TextField(default="")
	post_text = models.TextField(verbose_name='Текст статьи')
	pub_date = models.DateTimeField(default=timezone.now, verbose_name='Время публикации')
	post_img = models.FileField(upload_to='posts/', verbose_name='Картинка статьи')
	width_img = models.IntegerField(default=0, verbose_name='Ширина картинки')
	height_img = models.IntegerField(default=0, verbose_name='Длинна картинки')
	def __str__(self):
		return self.title

class Questions(models.Model):
	class Meta:
		verbose_name = 'Вопрос'
		verbose_name_plural = 'Вопросы'

	question_text = models.TextField(verbose_name='Текст вопроса')
	question_answer = models.TextField(verbose_name='Ответ', default='')
	question_img = models.FileField(upload_to='questions/',verbose_name='Картинка вопроса')
	pub_date = models.DateTimeField(default=timezone.now, verbose_name='Время публикации')
	width_img = models.IntegerField(default=0, verbose_name='Ширина картинки')
	height_img = models.IntegerField(default=0, verbose_name='Длинна картинки')

	def __str__(self):
		return self.question_text

content/views.py
from django.shortcuts import render
from .models import Posts, Questions
from django.views.generic import (View, TemplateView, ListView,
	DetailView, CreateView, UpdateView, DeleteView)

class IndexView(TemplateView):
	template_name = 'content/index.html'

class HomeView(TemplateView):
	template_name = 'content/home.html'

class PostListView(ListView):
	queryset = Posts.objects.order_by('-pub_date')
	template_name = 'content/posts.html'
	context_object_name = 'all_posts'
	paginate_by = 5

class PostView(DetailView):
	model = Posts
	template_name = 'content/post_detail.html'

class QuestionsView(ListView):
	queryset = Questions.objects.order_by('-pub_date')
	context_object_name = 'all_questions'
	template_name = 'content/questions.html'
	paginate_by = 10

class QuestionDetailView(DetailView):
	model = Questions
	template_name = 'content/question_detail.html'

class SolarView(TemplateView):
	template_name = 'content/solar.html'

content/templates/content/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
  {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'content/favicon.ico' %}">

    <title>{% block title %}{% endblock %}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'content/css/jumbotron-narrow.css' %} " rel="stylesheet">
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <h3 class="text-muted"><a href="{% url 'content:index' %}">Space In School</a></h3>
        <nav>
          <ul class="nav pull-right masthead-nav">
            <li role="presentation" class="{% block home-active %}{% endblock %}"><a href="{% url 'content:home' %}">Главная</a></li>
            <li role="presentation" class="{% block posts-active %}{% endblock %}"><a href="{% url 'content:post-list' %}">Статьи</a></li>
            <li role="presentation" class="{% block questions-active %}{% endblock %}"><a href="{% url 'content:questions' %}">Вопросы</a></li>
            <li role="presentation"><a href="{% url 'content:solar' %}">Солнечная система</a></li>
          </ul>
        </nav>
      </div>
      {% block body %}
      {% endblock %}
      <footer class="footer">
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->

    <script src="{% static 'content/js/script.js' %}"></script>

  </body>
</html>

content/templates/content/home.html
{% extends 'content/base.html '%}
{% block title %}Главная{% endblock %}
{% block home-active %}active{% endblock %}
{% block body %}
<div class="info">
	<h1>Главная страницa</h1>
	<p>Описание проекта</p>
</div>
{% endblock %}

content/templates/content/post_detail.html
{% extends 'content/base.html '%}
{% block title %}{{ posts.title }}{% endblock %}
{% block body %}
<div class="post">
	<h1>{{ posts.title }}</h1>
	<div class="mainImg">
	<img src="{{ posts.post_img.url }}" class="img-rounded" width="{{ posts.width_img }}" height="{{ posts.height_img }}">
	</div>
	{{ posts.post_text|safe }}
</div>
{% endblock %}

content/templates/content/posts.html
{% extends 'content/base.html '%}
{% block title %}Статьи{% endblock %}
{% block posts-active %}active{% endblock %}
{% block body %}
<div class="post">
	{% for post in all_posts %}
		<h1>{{ post.title }}</h1>
		<div class="mainImg">
			<img src="{{ post.post_img.url }}" class="img-rounded" width="{{ post.width_img }}" height="{{ post.height_img }}">
		</div>
		{{ post.post_short|safe }}
		<a href="{% url 'content:post' post.id %}">Показать полностью...</a>
		<hr>
	{% endfor %}
	<div class="pag">
		{% load bootstrap3 %}
		{% bootstrap_pagination page_obj %}
	</div>
</div>
{% endblock %}

content/templates/content/question_detail.html
{% extends 'content/base.html '%}
{% block title %}{{ questions.question_text }}{% endblock %}
{% block body %}
<div class="post">
	<h1>{{ questions.question_text }}</h1>
	<div class="mainImg">
	<img src="{{ questions.question_img.url }}" class="img-rounded" width="{{ questions.width_img }}" height="{{ questions.height_img }}">
	</div>
	{{ questions.question_answer|safe }}
</div>
{% endblock %}

content/templates/content/questions.html
{% extends 'content/base.html '%}
{% block title %}Вопросы{% endblock %}
{% block questions-active %}active{% endblock %}
{% block body %}
	<div class="question">
		{% for question in all_questions %}
			<h1><a href="{% url 'content:question-detail' question.id %}">{{ question.question_text }}</a></h1>
		{% endfor %}
	</div>
	<div class="pag">
		{% load bootstrap3 %}
		{% bootstrap_pagination page_obj %}
	</div>
{% endblock %}

content/templates/content/solar.html
<!DOCTYPE html>
<html>
<head>
	<title>Солнечная система</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'content/css/style.css' %}">
</head>
<body>
<div class="description">
		<h1>Solar System</h1>
	  <hr>
	  <p>
	    Это демонстрационный макет Солнечной системы
	  </p>
	  <hr>
	  <p><a href="{% url 'content:home' %}">Вернуться на главную</a></p>
  </div>
	<div class='solar-syst'>
	  <div class='sun'></div>
	  <div class='mercury'></div>
	  <div class='venus'></div>
	  <div class='earth'></div>
	  <div class='mars'></div>
	  <div class='jupiter'></div>
	  <div class='saturn'></div>
	  <div class='uranus'></div>
	  <div class='neptune'></div>
	  <div class='pluto'></div>
	  <div class='asteroids-belt'></div>
	</div>
</body>
</html>